'use strict';
const $=s=>document.querySelector(s), key='etched-invoicing-v1', money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toLocaleDateString('en-CA');
const future=()=>{let d=new Date();d.setDate(d.getDate()+30);return d.toLocaleDateString('en-CA')};
let state={business:{name:'Etched Laser Studio',website:'etchedstudio.vercel.app',terms:'Production starts after artwork approval. Please confirm materials, dimensions and spelling before approval.'},docs:[]}, current, toastTimer;
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&Array.isArray(saved.docs)&&saved.business)state=saved}catch{notify('Saved data could not be loaded. Restore a backup if needed.')}
function notify(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4000)}
function save(){try{localStorage.setItem(key,JSON.stringify(state));$('#save-status').textContent='Saved on this browser';}catch{$('#save-status').textContent='Saving unavailable — download a backup';}renderList()}
function reference(type){let prefix=type==='Quote'?'Q':'INV';let n=1;const refs=new Set(state.docs.map(d=>d.reference));while(refs.has(`${prefix}-${String(n).padStart(4,'0')}`))n++;return `${prefix}-${String(n).padStart(4,'0')}`}
function create(){current={id:crypto.randomUUID(),type:'Quote',reference:reference('Quote'),status:'Draft',date:today(),due:future(),customer:'',email:'',address:'',project:'',items:[{description:'',qty:1,price:0}],discount:0,delivery:0,vat:0,paid:0,notes:'',terms:state.business.terms||''};state.docs.unshift(current);save();render()}
function amount(v){return Math.round(Math.max(0,Number(v)||0)*100)/100}
function calc(d){const subtotal=d.items.reduce((n,i)=>n+Math.round(amount(i.qty)*amount(i.price)*100)/100,0),discount=Math.min(amount(d.discount),subtotal),delivery=amount(d.delivery),net=subtotal-discount+delivery,vat=Math.round(net*amount(d.vat))/100,total=Math.round((net+vat)*100)/100,paid=amount(d.paid);return{subtotal,discount,delivery,vat,total,paid,balance:Math.max(0,Math.round((total-paid)*100)/100),credit:Math.max(0,Math.round((paid-total)*100)/100)}}
function renderList(){$('#documents').innerHTML=state.docs.map(d=>`<button class="doc ${d.id===current?.id?'active':''}" data-id="${esc(d.id)}"><strong>${esc(d.reference)} · ${esc(d.type)}</strong><small>${esc(d.customer||'New customer')}</small><small>${esc(d.status)} · ${money(calc(d).total)}</small></button>`).join('')}
function render(){$('[data-field="type"]').value=current.type;document.querySelectorAll('[data-field]').forEach(e=>e.value=current[e.dataset.field]??'');renderItems();renderTotals();renderList();$('#title').textContent=current.type;$('#due-label').firstChild.textContent=current.type==='Quote'?'Valid until':'Payment due';$('#convert').hidden=current.type==='Invoice'}
function renderItems(){$('#items').innerHTML=current.items.map((i,n)=>`<div class="item"><textarea data-item="${n}" data-prop="description" aria-label="Item ${n+1} description" placeholder="Description, materials, dimensions" rows="1" maxlength="2000">${esc(i.description)}</textarea><input data-item="${n}" data-prop="qty" aria-label="Item ${n+1} quantity" type="number" min="0.01" step="0.01" value="${amount(i.qty)}"><input data-item="${n}" data-prop="price" aria-label="Item ${n+1} unit price" type="number" min="0" step="0.01" value="${amount(i.price)}"><span class="line-total">${money(Math.round(amount(i.qty)*amount(i.price)*100)/100)}</span><button data-remove="${n}" aria-label="Remove item ${n+1}">×</button></div>`).join('')}
function renderTotals(){const c=calc(current);$('#totals').innerHTML=`<div><span>Subtotal</span><span>${money(c.subtotal)}</span></div><div><span>Discount</span><span>−${money(c.discount)}</span></div><div><span>Delivery</span><span>${money(c.delivery)}</span></div><div><span>VAT (${amount(current.vat)}%)</span><span>${money(c.vat)}</span></div><div class="total"><span>Total</span><span>${money(c.total)}</span></div><div><span>Deposit / paid</span><span>${money(c.paid)}</span></div><div class="balance"><span>${current.type==='Quote'?'Remaining total':'Amount due'}</span><span>${money(c.balance)}</span></div>${c.credit?`<div><span>Overpayment</span><span>${money(c.credit)}</span></div>`:''}`}
$('.editor').addEventListener('input',e=>{const el=e.target;if(el.dataset.field){current[el.dataset.field]=el.type==='number'||el.dataset.field==='vat'?amount(el.value):el.value;if(el.dataset.field==='type'){current.reference=reference(current.type);current.status='Draft';render()}else renderTotals();save()}if(el.dataset.item!==undefined){current.items[Number(el.dataset.item)][el.dataset.prop]=el.dataset.prop==='description'?el.value:amount(el.value);el.closest('.item').querySelector('.line-total').textContent=money(Math.round(amount(current.items[el.dataset.item].qty)*amount(current.items[el.dataset.item].price)*100)/100);renderTotals();save()}});
$('#documents').onclick=e=>{let b=e.target.closest('[data-id]');if(b){current=state.docs.find(d=>d.id===b.dataset.id);render()}};
$('#new').onclick=create;$('#add-item').onclick=()=>{current.items.push({description:'',qty:1,price:0});save();renderItems()};$('#items').onclick=e=>{let b=e.target.closest('[data-remove]');if(b){current.items.splice(Number(b.dataset.remove),1);save();renderItems();renderTotals()}};
function copy(type=current.type){current=structuredClone(current);current.id=crypto.randomUUID();current.type=type;current.reference=reference(type);current.status='Draft';current.date=today();current.due=future();state.docs.unshift(current);save();render();notify(type==='Invoice'?'Invoice created. Original quote kept.':'Document duplicated')}
$('#duplicate').onclick=()=>copy();$('#convert').onclick=()=>copy('Invoice');$('#delete').onclick=()=>{if(!confirm('Delete this document from this browser? Download a backup first if you need a copy.'))return;state.docs=state.docs.filter(d=>d.id!==current.id);current=state.docs[0];if(!current)create();else{save();render()}};
$('#settings').onclick=()=>{for(let e of $('#business-form').elements)if(e.name)e.value=state.business[e.name]||'';$('#business-dialog').showModal()};$('#close-settings').onclick=()=>$('#business-dialog').close();$('#business-form').onsubmit=e=>{e.preventDefault();state.business=Object.fromEntries(new FormData(e.target));save();$('#business-dialog').close();notify('Business details saved')};
function download(blob,name){let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),10000)}
$('#backup').onclick=()=>download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),`etched-backup-${today()}.json`);
$('#restore').onchange=async e=>{try{let f=e.target.files[0];if(!f)return;if(f.size>5000000)throw Error('Backup is too large');let x=JSON.parse(await f.text());if(!x.business||typeof x.business!=='object'||!Array.isArray(x.docs)||!x.docs.every(d=>d&&typeof d.id==='string'&&['Quote','Invoice'].includes(d.type)&&Array.isArray(d.items)&&d.items.every(i=>i&&typeof i.description==='string')))throw Error('This is not a valid Etched backup');if(!confirm('Restore this backup? It will replace the documents saved in this browser.'))return;state=x;current=state.docs[0];if(!current)create();else{save();render()}notify('Backup restored')}catch(err){notify(err.message||'Could not restore backup')}e.target.value=''};
function dateLabel(s){if(!s)return '—';let d=new Date(s+'T12:00:00');return Number.isNaN(+d)?s:d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
$('#export').onclick=()=>{if(!current.customer.trim()||!current.reference.trim()){notify('Add a customer name and document reference first.');return}if(!current.items.length||current.items.some(i=>!i.description.trim()||amount(i.qty)<=0)){notify('Add a description and quantity for each line item.');return}try{exportPdf()}catch(err){console.error(err);notify('PDF could not be created. Please try again.')}};
function exportPdf(){const {jsPDF}=window.jspdf,pdf=new jsPDF({unit:'mm',format:'a4'}),b=state.business,d=current,c=calc(d);let y=22,page=1;const left=18,right=192;
function text(t,x,yy,size=10,bold=false){pdf.setFont('helvetica',bold?'bold':'normal');pdf.setFontSize(size);pdf.setTextColor(25,29,27);pdf.text(String(t||''),x,yy)}
function rule(){pdf.setDrawColor(220,224,221);pdf.line(left,y,right,y);y+=7}
function next(){pdf.addPage();page++;y=20;text(`${b.name} | ${d.type} ${d.reference}`,left,y,10,true);y+=12}
function ensure(h){if(y+h>274)next()}
function paragraph(t,size=10){pdf.setFont('helvetica','normal');pdf.setFontSize(size);let lines=pdf.splitTextToSize(String(t||''),174);for(let line of lines){ensure(6);text(line,left,y,size);y+=5.5}y+=4}
text('etched',left,y,30,true);pdf.setTextColor(255,99,43);pdf.text('.',51,y);text('L A S E R  S T U D I O',left,y+8,8,true);text(d.type.toUpperCase(),145,y,22,true);y+=21;text(b.name,left,y,11,true);text(d.reference,145,y,11,true);y+=7;paragraph([b.legal,b.address,b.email,b.phone,b.website,b.vatNumber?'VAT: '+b.vatNumber:'',b.companyNumber?'Company no: '+b.companyNumber:''].filter(Boolean).join('\n'),9);rule();text(d.type==='Quote'?'QUOTED TO':'BILL TO',left,y,9,true);y+=7;paragraph([d.customer,d.address,d.email].filter(Boolean).join('\n'));text(`Issued: ${dateLabel(d.date)}    ${d.type==='Quote'?'Valid until':'Payment due'}: ${dateLabel(d.due)}`,left,y,10);y+=8;if(d.project){paragraph('Project / order: '+d.project)}rule();
function tableHead(){text('Description',left,y,9,true);text('Qty',128,y,9,true);text('Unit £',148,y,9,true);text('Total £',176,y,9,true);y+=7}
tableHead();for(const i of d.items){pdf.setFontSize(10);let lines=pdf.splitTextToSize(i.description,100);let first=true;for(let offset=0;offset<lines.length;){let capacity=Math.floor((268-y)/5.5);if(capacity<2){next();tableHead();capacity=Math.floor((268-y)/5.5)}let take=lines.slice(offset,offset+capacity);if(first){text(amount(i.qty),128,y);text(amount(i.price).toFixed(2),148,y);text((Math.round(amount(i.qty)*amount(i.price)*100)/100).toFixed(2),176,y);first=false}for(let line of take){text(line,left,y);y+=5.5}offset+=take.length;}y+=5;}ensure(65);rule();for(let [label,value] of [['Subtotal',c.subtotal],['Discount',-c.discount],['Delivery',c.delivery],[`VAT (${amount(d.vat)}%)`,c.vat],['Total',c.total],['Deposit / paid',c.paid],[d.type==='Quote'?'Remaining total':'Amount due',c.balance]]){text(label,115,y,10,label==='Total'||label==='Amount due');pdf.setFontSize(10);pdf.text(money(value),right,y,{align:'right'});y+=7}if(c.credit){text('Overpayment',115,y);pdf.text(money(c.credit),right,y,{align:'right'});y+=7}y+=8;if(d.notes){ensure(16);text('NOTES / SCOPE',left,y,9,true);y+=7;paragraph(d.notes)}if(d.terms){ensure(16);text('TERMS & PAYMENT',left,y,9,true);y+=7;paragraph(d.terms)}for(let n=1;n<=pdf.getNumberOfPages();n++){pdf.setPage(n);pdf.setDrawColor(220,224,221);pdf.line(left,283,right,283);text(`${d.type} ${d.reference}`,left,290,8);text(`Page ${n} of ${pdf.getNumberOfPages()}`,165,290,8)}download(pdf.output('blob'),`${d.type}-${d.reference.replace(/[^a-z0-9_-]/gi,'-')}.pdf`);notify('PDF downloaded')}
if(state.docs.length){current=state.docs[0];render()}else create();
